import SwiftUI

enum AppSection: String, CaseIterable, Identifiable { case overview, materials, mechanisms, standards, components, sources, claims, relationships
 var id: Self { self }; var title: String { switch self { case .overview:"Overview"; case .materials:"Materials"; case .mechanisms:"Damage Mechanisms"; case .standards:"Standards"; case .components:"Components"; case .sources:"Sources"; case .claims:"Claims"; case .relationships:"Relationships" } }
 var kind: RecordKind? { switch self { case .materials:.material; case .mechanisms:.mechanism; case .standards:.standard; case .components:.component; case .sources:.source; default:nil } }
}

struct RootView: View { @State private var selection: AppSection? = .overview; @State private var store: KnowledgeStore?; @State private var error: String?; @State private var refresh = UUID()
 var body: some View { NavigationSplitView { List(AppSection.allCases, selection: $selection) { Label($0.title, systemImage: "circle").tag(Optional($0)) }.navigationTitle("Materials Intelligence").listStyle(.sidebar) } detail: { if let selection { Page(section: selection, store: store, refresh: $refresh, error: error) } }.frame(minWidth: 980, minHeight: 640).task { do { let s = try KnowledgeStore(url: try KnowledgeStore.applicationURL()); try s.seedIfEmpty(); store=s } catch let caught { error=caught.localizedDescription } } }
}

private struct Page: View { let section: AppSection; let store: KnowledgeStore?; @Binding var refresh: UUID; let error: String?
 var body: some View { Group { if let error { ContentUnavailableView("Database unavailable", systemImage:"externaldrive.badge.exclamationmark", description:Text(error)) } else if let store { if let kind=section.kind { RecordPage(kind:kind, store:store, refresh:$refresh) } else if section == .claims { ClaimsPage(store:store, refresh:$refresh) } else if section == .relationships { RelationshipsPage(store:store, refresh:$refresh) } else { Overview(store:store) } } else { ProgressView("Opening local knowledge") } }.toolbar { Button("Refresh", systemImage:"arrow.clockwise") { refresh=UUID() } } }
}

private struct Overview: View { let store: KnowledgeStore; var body: some View { VStack(alignment:.leading,spacing:18) { Text("Knowledge workspace").font(.largeTitle.bold()); Text("Create structured records, preserve source traceability, and review claims locally.").foregroundStyle(.secondary); ForEach(RecordKind.allCases,id:\.self) { k in LabeledContent(k.rawValue.capitalized,value:"\((try? store.records(kind:k).count) ?? 0)") }; Text("Sample records are illustrative and unverified.").font(.caption).foregroundStyle(.secondary) }.frame(maxWidth:700,alignment:.leading).padding(32) } }

private struct RecordPage: View { let kind:RecordKind; let store:KnowledgeStore; @Binding var refresh:UUID; @State private var selected:KnowledgeRecord?; @State private var editor:KnowledgeRecord?; @State private var adding=false; @State private var alert=""; var records:[KnowledgeRecord] {(try? store.records(kind:kind)) ?? []}
 var body: some View { HStack(spacing:0) { List(records,selection:$selected) { r in VStack(alignment:.leading){Text(r.name);Text(r.secondary).font(.caption).foregroundStyle(.secondary)}.tag(r) }.frame(width:300);Divider(); if let selected { RecordDetail(record:selected,store:store,edit:{editor=selected},delete:delete) } else { ContentUnavailableView("Select a record",systemImage:"doc.text") } }.navigationTitle(kind.rawValue.capitalized).toolbar { Button("Add",systemImage:"plus"){adding=true} }.sheet(isPresented:$adding){RecordEditor(kind:kind,store:store,done:{refresh=UUID()})}.sheet(item:$editor){RecordEditor(record:$0,store:store,done:{refresh=UUID()})}.alert("Cannot delete record",isPresented:Binding(get:{!alert.isEmpty},set:{if !$0{alert=""}})){Button("OK"){} } message:{Text(alert)} }
 func delete(){guard let selected else{return};do{try store.deleteRecord(id:selected.id);self.selected=nil;refresh=UUID()}catch{alert="This record is referenced by a claim or relationship. Remove those references first; knowledge is never silently destroyed."}}
}
private struct RecordDetail: View { let record:KnowledgeRecord;let store:KnowledgeStore;let edit:()->Void;let delete:()->Void; var body:some View{ScrollView{VStack(alignment:.leading,spacing:16){HStack{Text(record.name).font(.largeTitle.bold());Spacer();Button("Edit",action:edit);Button("Delete",role:.destructive,action:delete)};Text(record.secondary).font(.headline);Text(record.detail.isEmpty ? "No detail recorded.":record.detail);Divider();Text("Claims").font(.title2.bold());ForEach((try? store.claims(subjectID:record.id)) ?? []){Text("\($0.status.title): \($0.statement)")};Text("Relationships").font(.title2.bold());ForEach((try? store.relationships(recordID:record.id)) ?? []){let id=$0.fromID==record.id ? $0.toID:$0.fromID;Text("\($0.predicate.replacingOccurrences(of:"_",with:" ")) → \((try? store.record(id:id))?.name ?? "Unknown")")}}.frame(maxWidth:.infinity,alignment:.leading).padding(28)}}}
private struct RecordEditor: View { @Environment(\.dismiss)var dismiss;let record:KnowledgeRecord?;let kind:RecordKind;let store:KnowledgeStore;let done:()->Void;@State var name="";@State var detail="";@State var secondary="";@State var error="";init(record:KnowledgeRecord?=nil,kind:RecordKind?=nil,store:KnowledgeStore,done:@escaping()->Void){self.record=record;self.kind=record?.kind ?? kind!;self.store=store;self.done=done;_name=State(initialValue:record?.name ?? "");_detail=State(initialValue:record?.detail ?? "");_secondary=State(initialValue:record?.secondary ?? "")}
 var body:some View{Form{TextField("Name",text:$name);TextField("Designation / revision",text:$secondary);TextField("Detail",text:$detail,axis:.vertical);Text(error).foregroundStyle(.red)}.padding().frame(width:460).toolbar{ToolbarItem(placement:.cancellationAction){Button("Cancel"){dismiss()}};ToolbarItem(placement:.confirmationAction){Button("Save"){save()}.disabled(name.trimmingCharacters(in:.whitespacesAndNewlines).isEmpty)}}}
 func save(){do{try store.save(KnowledgeRecord(id:record?.id ?? UUID().uuidString,kind:kind,name:name.trimmingCharacters(in:.whitespacesAndNewlines),detail:detail,secondary:secondary));done();dismiss()}catch let caught{error=caught.localizedDescription}}
}

private struct ClaimsPage: View { let store: KnowledgeStore; @Binding var refresh: UUID; @State private var selected: EngineeringClaim?; @State private var adding=false
 var claims:[EngineeringClaim] {(try? store.claims()) ?? []}; var body:some View { VStack(alignment:.leading){List(claims,selection:$selected){c in VStack(alignment:.leading){Text(c.statement);Text("\(c.status.title) · \((try? store.record(id:c.sourceID))?.name ?? "Unknown source")").font(.caption).foregroundStyle(.secondary)}.tag(c)} }.navigationTitle("Engineering Claims").toolbar{Button("Add",systemImage:"plus"){adding=true}}.sheet(isPresented:$adding){ClaimEditor(store:store,done:{refresh=UUID()})} }
}
private struct ClaimEditor: View { @Environment(\.dismiss)var dismiss; let store:KnowledgeStore; let done:()->Void; @State var subject="";@State var statement="";@State var predicate="";@State var source="";@State var locator="";@State var status:VerificationStatus = .draft;@State var error=""; var body:some View{Form{Picker("Subject",selection:$subject){ForEach((try? store.records()) ?? []){Text($0.name).tag($0.id)}};Picker("Source",selection:$source){ForEach((try? store.records(kind:.source)) ?? []){Text($0.name).tag($0.id)}};TextField("Predicate",text:$predicate);TextField("Statement",text:$statement,axis:.vertical);TextField("Page / section",text:$locator);Picker("Review state",selection:$status){ForEach(VerificationStatus.allCases,id:\.self){Text($0.title).tag($0)}};Text(error).foregroundStyle(.red)}.padding().frame(width:520).toolbar{ToolbarItem(placement:.cancellationAction){Button("Cancel"){dismiss()}};ToolbarItem(placement:.confirmationAction){Button("Save"){save()}.disabled(subject.isEmpty||source.isEmpty||statement.isEmpty)}}}
 func save(){do{try store.save(EngineeringClaim(subjectID:subject,predicate:predicate,statement:statement,sourceID:source,locator:locator,status:status));done();dismiss()}catch let caught{error=caught.localizedDescription}}
}
private struct RelationshipsPage: View { let store:KnowledgeStore; @Binding var refresh: UUID; @State var adding=false; var body:some View{List((try? store.relationships()) ?? []){r in let f=(try? store.record(id:r.fromID))?.name ?? "?";let t=(try? store.record(id:r.toID))?.name ?? "?";Text("\(f)  —  \(r.predicate.replacingOccurrences(of:"_",with:" "))  —  \(t)")}.navigationTitle("Relationships").toolbar{Button("Add",systemImage:"plus"){adding=true}}.sheet(isPresented:$adding){RelationshipEditor(store:store,done:{refresh=UUID()})}}
}
private struct RelationshipEditor: View { @Environment(\.dismiss)var dismiss;let store:KnowledgeStore;let done:()->Void;@State var from="";@State var to="";@State var predicate="related_to";@State var error="";var body:some View{Form{Picker("From",selection:$from){ForEach((try? store.records()) ?? []){Text($0.name).tag($0.id)}};TextField("Relationship",text:$predicate);Picker("To",selection:$to){ForEach((try? store.records()) ?? []){Text($0.name).tag($0.id)}};Text(error).foregroundStyle(.red)}.padding().frame(width:430).toolbar{ToolbarItem(placement:.cancellationAction){Button("Cancel"){dismiss()}};ToolbarItem(placement:.confirmationAction){Button("Save"){save()}.disabled(from.isEmpty||to.isEmpty||from==to)}}}
 func save(){do{try store.save(KnowledgeRelationship(fromID:from,predicate:predicate,toID:to));done();dismiss()}catch let caught{error=caught.localizedDescription}}
}
